### ISSUE TITLE
notifications are broken again

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#276]
No new notifications are generated. This is realy a problem, because meanwhile we have continuous community interaction and they aren't notified, if we answer their comments and review their edits.

In my top navigation, it says, I have 5 "unsolved/not viewed" notifications. But I already clicked at all of them. The 5 doesn't go away. It's the same with other profiles

![5](https://cloud.githubusercontent.com/assets/3379377/12222076/49d38a44-b7b1-11e5-933c-0cd5c148b5ab.PNG)

**Comment by arekkas** [comment]
the first one should be fixed

**Comment by arekkas** [comment]
the latter's backtrace:

1. https://github.com/serlo-org/athene2/blob/5af370476278403b822d2073d52d62fec958c630/src/module/Notification/src/Notification/Controller/NotificationController.php#L39
2. https://github.com/serlo-org/athene2/blob/5af370476278403b822d2073d52d62fec958c630/src/module/Notification/src/Notification/NotificationManager.php#L72-L84
3. https://github.com/serlo-org/athene2/blob/5af370476278403b822d2073d52d62fec958c630/src/module/Notification/src/Notification/NotificationManager.php#L62-L70

Instead of using the default limit of 20 `public function findNotificationsBySubscriber(UserInterface $user, $limit = 20)` set a high number [here](https://github.com/serlo-org/athene2/blob/5af370476278403b822d2073d52d62fec958c630/src/module/Notification/src/Notification/NotificationManager.php#L74)
