### ISSUE TITLE
`entity/trash-bin` and `entity/unrevised` behave weird.

### ISSUE THREAD

**Issue by inyono** [serlo-org/athene2#283]
Steps to reproduce:
- Go to math trash-bin: https://de.serlo.org/mathe/entity/trash-bin
- Go to math unrevised: https://de.serlo.org/mathe/entity/unrevised
- If necessary, go back to trash-bin

The title changes but the list of items stays the same. @TinsayeAbye reported that yesterday both lists showed the trashed entities. But today, both lists show the unrevised entities. Maybe some problem with caching? Since both trash-bin and unrevised only load slow on the initial load. Furthermore, there seems to be no difference between routing on the real page or opening the pages in new tabs. Problem occurs across all relevant browsers.

**Comment by Knorrke** [comment]
This is still an issue and probably caused by using the same key in storage for trash-bin and unrevised entities, see:
https://github.com/serlo-org/athene2/blob/d8468f179ac8234f80925c277528f6fe7af32b40/src/module/Subject/src/Subject/Manager/SubjectManager.php#L65-L70
and 
https://github.com/serlo-org/athene2/blob/d8468f179ac8234f80925c277528f6fe7af32b40/src/module/Subject/src/Subject/Manager/SubjectManager.php#L79-L85
