### ISSUE TITLE
Improve workflow for trashed entities

### ISSUE THREAD

**Issue by inyono** [serlo-org/athene2#370]
* [ ] When the user tries to edit an trashed entity, show a message instead of the current 404 error. E.g. "This content is trashed. If you want to edit it, restore it beforehand."
* [x] When the user tries to add a child and it fails because there is already a trashed child of the given type (e.g. hints, solutions, input-challenges, single-choice-correct-answer), do basically the same as above (with appropriate message).
* [x] Hide trashed children, e.g. don't show "Show solution" if the solution is trashed. Same for hints, input-challenges, ...
* [x] Hide trashed entities in batch copy/move
* [x] Hide trashed entities in taxonomy reordering
* [ ] Review workflow for courses, see discussion in #268 

also related: #95, #319

**Comment by Knorrke** [comment]
This solution hides all trashed children (solution, hints, SC/MC, input) and entities (in batch copy/move and in taxonomy reordering). It also introduces a restore action (instead of add) for trashed elements, so you can restore trashed children without searching in the trash bin.

I don't know if the problems of #268 are solved with this, @inyono maybe you could have a look?
