### ISSUE TITLE
include header and new subjects on starting page

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#420]
changes to serlo.org/:
- add header
- add three more subjects
- delete press section
- Update from Sprint Planning: replace numbers (blue section) with project description and link to serlo.org/serlo. So only partners remain below subject selection

Mock up: https://docs.google.com/drawings/d/1rmTtmv0rKjhGNFaXEZD6itr6VnOvtT3wK9bcNKn_bKQ/edit

dependencies until pr:
- visuals for the subjects from vasiliki
- final go from Botho (design)
- final go from Simon (content)

**Comment by JonasBley** [comment]
Here are a few screenshots, what do you think?
![startseite1](https://cloud.githubusercontent.com/assets/14056541/19072758/40ffc1a4-8a37-11e6-89eb-fbef77119dbe.PNG)
Maybe more space between partners and the blue row and less space between subjects and partners?
![startseite2](https://cloud.githubusercontent.com/assets/14056541/19072759/41ada968-8a37-11e6-902c-ddf59f4b7a2b.PNG)
Here the link when hovering over it: (the color changes to serloblue)
![startseite3](https://cloud.githubusercontent.com/assets/14056541/19072760/42bf214c-8a37-11e6-9f7a-62224b2e7d52.png)

**Comment by arekkas** [comment]
Awesome, that looks much better already! The hover link disappears with the serlo blue in the background, maybe keep it white and underline or something like that?

**Comment by arekkas** [comment]
I'm guessing that the other subjects are placed that way because they have no logo, right?

**Comment by SimonKoehl** [comment]
Great, @JonasBley My Feedback:
- make Logo and header litte bigger
- "Die freie Lernplattform" should have the same size (hight of the letters) as "Serlo"
- litte less distance between top navigation and header

@arekkas grafics for subjects are work in progress by Vasiliki

**Comment by JonasBley** [comment]
![screenshot 2016-10-04 16 19 46](https://cloud.githubusercontent.com/assets/14056541/19077887/80b6f3a0-8a4e-11e6-9171-9d4b6cb66f27.png)
![screenshot 2016-10-04 16 19 35](https://cloud.githubusercontent.com/assets/14056541/19077889/80b9c15c-8a4e-11e6-853f-86659bf25595.png)
![screenshot 2016-10-04 16 19 56](https://cloud.githubusercontent.com/assets/14056541/19077890/80c15124-8a4e-11e6-8dec-a3ff335230db.png)

**Comment by JonasBley** [comment]
Sorry, forgot the little less distance between top navigation and header. Better like this?
![screenshot 2016-10-04 16 22 54](https://cloud.githubusercontent.com/assets/14056541/19077976/d6932a3c-8a4e-11e6-9361-be12f3eca1db.png)

**Comment by JonasBley** [comment]
@arekkas yes the other subjects would be placed like "Mathematik lernen" once the logos are there

**Comment by arekkas** [comment]
There should be a separation between Serlo and Die Freie Lernplatform as fonts don't match either in weight, nor in style nor in family. This should probably be prototyped in photoshop rather than htmlcss

**Comment by JonasBley** [comment]
I agree with @arekkas 
This is what I have now, the brand and the text weren't aligned to the bottom:
![diefreielernplattform](https://cloud.githubusercontent.com/assets/14056541/19078541/c7cc4784-8a50-11e6-94dd-b11a50984fc0.PNG)

**Comment by SimonKoehl** [comment]
@JonasBley nice

Did you receive the information, that @Knorrke updated the logo font (text and bird)

**Comment by JonasBley** [comment]
I didn't know that, is the updated logo and font already on de.serlo.org/mathe? Then I can copy it from there.

**Comment by Knorrke** [comment]
Yes it is, but i think it should be updated everywhere because I changed the font-files. It just might change some positioning of the logo.

**Comment by elbotho** [comment]
The graphics are nearly done.

This is the default state. 
![image](https://cloud.githubusercontent.com/assets/1258870/20145180/66d5f1bc-a69f-11e6-922d-3027328d3384.png)
On hover (or on mobile) they change colors. eg:

![image](https://cloud.githubusercontent.com/assets/1258870/20145251/a73d8be8-a69f-11e6-99e9-bd376a72511b.png)

I attached the svgs here. They have simple css stuff in there to mockup the hover. I suggest to embed the svgs in a way that we can just change the colors via css. (check [this article](https://css-tricks.com/using-svg/) for good information about that)

**SVG Files:**
[starting_page_illus.zip](https://github.com/serlo-org/athene2/files/581296/starting_page_illus.zip)

**Comment by JonasBley** [comment]
Nice, thanks! I'll see what I can do with it

Am 9. November 2016, um 17:16, Botho <notifications@github.com> schrieb:

The graphics are nearly done.

This is the default state. 
￼
On hover (or on mobile) they change colors. eg:

￼

I attached the svgs here. They have simple css stuff in there to mockup the hover. I suggest to embed the svgs in a way that we can just change the colors via css. (check this article for good information about that)

SVG Files:
starting_page_illus.zip

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/serlo-org/athene2","title":"serlo-org/athene2","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/serlo-org/athene2">https://github.com/serlo-org/athene2</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@elbotho in #420: The graphics are nearly done.\r\n\r\nThis is the default state. \r\n![image](<a href="https://cloud.githubusercontent.com/assets/1258870/20145180/66d5f1bc-a69f-11e6-922d-3027328d3384.png">https://cloud.githubusercontent.com/assets/1258870/20145180/66d5f1bc-a69f-11e6-922d-3027328d3384.png</a>)\r\nOn hover (or on mobile) they change colors. eg:\r\n\r\n![image](<a href="https://cloud.githubusercontent.com/assets/1258870/20145251/a73d8be8-a69f-11e6-99e9-bd376a72511b.png">https://cloud.githubusercontent.com/assets/1258870/20145251/a73d8be8-a69f-11e6-99e9-bd376a72511b.png</a>)\r\n\r\nI attached the svgs here. They have simple css stuff in there to mockup the hover. I suggest to embed the svgs in a way that we can just change the colors via css. (check [this article](<a href="https://css-tricks.com/using-svg">https://css-tricks.com/using-svg</a>/) for good information about that)\r\n\r\n**SVG Files:**\r\n[starting_page_<a href="http://illus.zip">illus.zip</a>](<a href="https://github.com/serlo-org/athene2/files/581296/starting_page_illus.zip">https://github.com/serlo-org/athene2/files/581296/starting_page_illus.zip</a>)\r\n\r\n"}],"action":{"name":"View Issue","url":"<a href="https://github.com/serlo-org/athene2/issues/420#issuecomment-259454353">https://github.com/serlo-org/athene2/issues/420#issuecomment-259454353</a>"}}}

**Comment by Knorrke** [comment]
@JonasBley contact me if you need help with this

**Comment by JonasBley** [comment]
![screenshot 2016-11-13 23 17 01](https://cloud.githubusercontent.com/assets/14056541/20249310/593473b6-a9f7-11e6-8200-0fbd5af25fc6.png)
![screenshot 2016-11-13 23 16 51](https://cloud.githubusercontent.com/assets/14056541/20249309/5932d006-a9f7-11e6-8ad0-ca2bf0150725.png)
![screenshot 2016-11-13 23 17 11](https://cloud.githubusercontent.com/assets/14056541/20249311/593633b8-a9f7-11e6-85f4-31455f884a8b.png)

What do you think of not using arrows?

**Comment by SimonKoehl** [comment]
could be tested with A/B, if they are necessary. But i would start with integrating them because we have a lot of free text/icon Elements, that cant't be clicked, so the arrows should help us to signal, "this can be clilcked". @elbotho what do you think?

**Comment by JonasBley** [comment]
Imo the blue arrows look out of place now that the logos are colourless. Maybe black arrows that turn blue on hover? I'll provide screenshots with arrows in the next days

**Comment by JonasBley** [comment]
![pasted image at 2016_11_14 09_32 am 1](https://cloud.githubusercontent.com/assets/14056541/20258170/901bb78e-aa4e-11e6-8813-0494e0de58a8.png)
![pasted image at 2016_11_14 09_32 am](https://cloud.githubusercontent.com/assets/14056541/20258171/917f5270-aa4e-11e6-98ca-10811327f34f.png)
![pasted image at 2016_11_14 09_43 am](https://cloud.githubusercontent.com/assets/14056541/20258221/e3b7644c-aa4e-11e6-93a6-f811ed1949a6.png)

**Comment by SimonKoehl** [comment]
@JonasBley looks good, I favour the darker verison

**Comment by JonasBley** [comment]
![screenshot 2016-11-24 16 33 25](https://cloud.githubusercontent.com/assets/14056541/20603973/56ffac80-b264-11e6-8a16-1bf46073157f.png)
![screenshot 2016-11-24 16 33 30](https://cloud.githubusercontent.com/assets/14056541/20603976/5a516f40-b264-11e6-877e-86ccd4744214.png)
![screenshot 2016-11-24 16 29 42](https://cloud.githubusercontent.com/assets/14056541/20603986/6517db6c-b264-11e6-9780-da14e800adec.png)
![screenshot 2016-11-24 16 29 49](https://cloud.githubusercontent.com/assets/14056541/20603989/6bf29026-b264-11e6-8878-ba8a09c114f1.png)

**Comment by JonasBley** [comment]
Could make the subjects bigger maybe?

**Comment by elbotho** [comment]
I like the last version as well. Dark gray arrows.
I'll add cudos to @SimonKoehl and myself and make sure vasiliki gets hers 😺 

It's a detail, but with the arrows on the right the illustrations are not centered above the text so I'd suggest putting them
* below in the next line (centered)
* or in the second line (inline with 1 or 2 spaces to the text) 

what do you think?

**Comment by elbotho** [comment]
Vasiliki would prefer the illustrations a bit bigger and the arrows centered.

**Comment by SimonKoehl** [comment]
looks great @JonasBley !

Input from @elbotho : the subjects should be blue on mobile (without mouse over)

considering the arrows, @elbotho 's second suggestions works quite well, see screenshot
![home_arrows inline](https://cloud.githubusercontent.com/assets/3379377/20608999/93d32402-b287-11e6-8d94-672a646381a3.png)

**Comment by Knorrke** [comment]
@elbotho I think we could also center the logos above the text, if you think that's the best option. Of course your two options would work too

**Comment by Knorrke** [comment]
would look like this:
![bildschirmfoto vom 2016-11-24 22 19 32](https://cloud.githubusercontent.com/assets/11499926/20610022/3300cd5c-b294-11e6-879d-52f78bb234ce.png)
