### ISSUE TITLE
please add two logos to main partners on landing page

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#480]
new order: TU, EU, LMU, HSS, WM

here are the svgs
https://drive.google.com/a/serlo.org/file/d/0B0vgO6Y0XakNTThNejBiR1dobHM/view?usp=sharing
https://drive.google.com/a/serlo.org/file/d/0B0vgO6Y0XakNS3hGN1VrZ0dZbUU/view?usp=sharing

**Comment by JonasBley** [comment]
First, I am not sure whether this is for the current landing page or the planned one (see #471). 
The following is only relevant, if it's for the current landing page.

The EU logo will look alright, but the blue should be the same as on Serlo and also there should be a white border around the flag. 

The LMU logo is green though, also the background isn't transparent. I am not sure whether that will fit so well into the page. I would suggest the following:
1) make it blue instead of green
2) have white borders for the boxes
3) make the background transparent
Would these changes be ok?
My skills with graphic design programs are very limited and I don't have a lot of free time, so I won't be able to implement these changes to the svgs myself.

**Comment by SimonKoehl** [comment]
Hi Jonas, it's only important for the new landing page.

Have a look, how @elbotho formated the logo svgs on the current landing pages. Ithink it is a mixture between gray-scale and transparency-scale. They shouldn't have collors

**Comment by SimonKoehl** [comment]
oh and @JonasBley I would suggest to keep the replacement of the partners, that Botho did on the new landing page, too. So place them at the bottom of the second section (background picture). What do you think?

**Comment by JonasBley** [comment]
Oh I see, it is already a big white border around the LMU logo.

**Comment by JonasBley** [comment]
I would prefer them in the second section too. Makes more sense, thematically, to put partners below the vision.

**Comment by JonasBley** [comment]
We are kind of having a conversation in two different, issues, this all belongs to #471 right?

**Comment by Knorrke** [comment]
done in #489
