### ISSUE TITLE
diverse fatal errors in en.serlo.org/backend

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#605]
fatal error trying to reach the recycle bin: https://en.serlo.org/uuid/recycle-bin

fatal error trying to reach this topic: https://en.serlo.org/wiki/start-new-serlo-education-team

fatal error trying to rename the subjet "wiki" to "community": https://en.serlo.org/taxonomy/term/organize-all

Also there is still a type "forum" called "community". I tried to rename this first (to "community old"). But that also led to a fatal error

also creating a new subject "community" leads to a fatal error

**Comment by arekkas** [comment]
> fatal error trying to reach the recycle bin: https://en.serlo.org/uuid/recycle-bin

Not reproducible

> fatal error trying to reach this topic: https://en.serlo.org/wiki/start-new-serlo-education-team

Not reproducible

> fatal error trying to rename the subjet "wiki" to "community": https://en.serlo.org/taxonomy/term/organize-all
> also creating a new subject "community" leads to a fatal error

This is most likely caused by

> Also there is still a type "forum" called "community". I tried to rename this first (to "community old"). But that also led to a fatal error

**Comment by arekkas** [comment]
> fatal error trying to reach the recycle bin: https://en.serlo.org/uuid/recycle-bin

Now it's reproducible:

![image](https://user-images.githubusercontent.com/3372410/31719912-46ad2ea8-b415-11e7-9996-ab3672c72ba9.png)

**Comment by arekkas** [comment]
> fatal error trying to reach this topic: https://en.serlo.org/wiki/start-new-serlo-education-team

This is caused by the subject wiki being missing.

![image](https://user-images.githubusercontent.com/3372410/31719966-77d95d3a-b415-11e7-8eb9-69d028c6e6b1.png)

> Also there is still a type "forum" called "community". I tried to rename this first (to "community old"). But that also led to a fatal error

This is because forum is no longer allowed as a taxonomy type, you need to remove it completely

Error:

![image](https://user-images.githubusercontent.com/3372410/31720022-aaa79d58-b415-11e7-88ac-7339aa31ca31.png)

If you encounter such errors next time, it would be great to stop your work on it as those are cascading and harder to de-tangle the more you work into it

**Comment by SimonKoehl** [comment]
ok - sorry!

**Comment by arekkas** [comment]
Did you by any chance delete some comments or something like that on the english tenant?

**Comment by SimonKoehl** [comment]
no, the forum taxonomy element was the only thing I tried to delete

**Comment by arekkas** [comment]
https://github.com/serlo-org/athene2/issues/605#issuecomment-337582727 is most likely caused by our access control system, and by a comment which isn't associated with an instance (no idea how that can happen). I'll check out in the database if it's only one comment and will hotfix it, otherwise we have to do some code changes.

**Comment by arekkas** [comment]
There appears to be no comment without an instance, so it's most likely a code bug:

```
> select * from comment where instance_id IS NULL;
Empty set (0.00 sec)
```

**Comment by SimonKoehl** [comment]
We have some important dependencies on this sissue now ..

**Comment by SimonKoehl** [comment]
so we can close this issue @arekkas ?
