### ISSUE TITLE
recycle bin has no ui

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/athene2#637]
https://en.serlo.org/uuid/recycle-bin

**Comment by Knorrke** [comment]
Same problem exists in the german tenant.

@inyono it works in the local environment, any idea why this happens? It seems like the template is loaded without layout...

**Comment by inyono** [comment]
@Knorrke Didn't we have a lead / fix for that?

**Comment by Knorrke** [comment]
I did work on it, not sure how far I got with it... I'll check if I have some code lying around.

**Comment by Knorrke** [comment]
Ok, @inyono resolved this yesterday in the database... this was caused by some entries in the `uuid` table, which didn't have a corresponding entry in the referenced table (e.g. `taxonomy_term` and `comment`)

It looks like there are some 'holes' in the database, where the old forum system was... I opened a new issue for that: #755
