### ISSUE TITLE
List of unrevised editings shows old stuff

### ISSUE THREAD

**Issue by inyono** [serlo-org/athene2#659]
see https://de.serlo.org/mathe/entity/unrevised
* [ ] shows some old unrevised editings (2 years ago)
* [ ] isn't sorted by timestamp

**Comment by Knorrke** [comment]
ping @inyono the old editings seem to be gone by now? Are you suggesting, only to show unrevised editings from a certain timespan?

Also might be related (or causing this): When there are multiple unrevised editings on the same entity, rejecting the newest one won't remove the entity from the list, since there are unrevised editings before that point. Annoyingly the link leads to the newest editing anyway, so it seems like it's already done when visited.
A solution might be to check only the newest version? Maybe this could also improve the load time of the page?

**Comment by Knorrke** [comment]
Might also be caused by #283, so showing the trash-bin instead of the unrevised edtitings?

**Comment by Knorrke** [comment]
@inyono Can we close this, assuming that the old entries weren't actually revisions, but from trash-bin (#283, which is fixed by now)?

**Comment by inyono** [comment]
Yes
