### ISSUE TITLE
de.serlo.org doesn't work on iOS

### ISSUE THREAD

**Issue by inyono** [serlo-org/athene2#89]
Both in Safari and Chrome, opening `https://de.serlo.org` redirects to `https://de.serlo.org/^[%20/t/r/n/f]+|[%20/t/r/n/f]+$/g`

Edit: it works locally, though (using vagrantshare)

**Comment by arekkas** [comment]
could be caused by cloudflare

**Comment by arekkas** [comment]
this is reproducible when using the ios simulator and the latest iphone

**Comment by arekkas** [comment]
It looks like this was caused by `webcomponents.js`, which has been solve here: 17484c95037f923fe42d819df05e14074ed4c689

**Comment by nazar-pc** [comment]
CloudFlare passes `window.location` object to `window.URL` constructor while [constructor accepts only strings](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL), which is why https://github.com/webcomponents/webcomponentsjs/blob/c9bceeedb4077b5658d95f5755883592be92fcaf/src/URL/URL.js#L473 works very differently and causes this error, meaning redirect to another page instead of string replace.

CloudFlare already notified about this, hope they'll fix it soon.

**Comment by arekkas** [comment]
Thanks for tracking this down!!

**Comment by terinjokes** [comment]
@nazar-pc this still doesn't make sense, just a few lines beforehand the base property is Stringified and converted to a jURL instance.

https://github.com/webcomponents/webcomponentsjs/blob/c9bceeedb4077b5658d95f5755883592be92fcaf/src/URL/URL.js#L468

**Comment by nazar-pc** [comment]
@terinjokes, regexp works with `url` variable, `base` is not relevant there.

**Comment by terinjokes** [comment]
@nazar-pc I fixed this a while ago, but just came across this thread, I forgot what I was doing. Sorry, carry along. :)
